# Generated by Django 5.2.7 on 2025-10-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='main_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
