# Generated by Django 5.2.7 on 2025-10-21 14:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_remove_place_images_alter_place_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
